name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          # remove labels if changes are no longer impacting the previous files
          sync-labels: true