# This is a fix for the following known issue:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Just a check for Merge Queues

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

  # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
  merge_group:
    types: [ checks_requested ]

concurrency:
  # github.workflow: this workflow type
  # github.event.pull_request.id: if this is a pull request, this pull request's id
  #   https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
  group: "workflow = ${{ github.workflow }}, pr = ${{ github.event.pull_request.id }}"
  # we only want to cancel on pull_request
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "Path filters workaround: No build required"
          echo "Path filters workaround: No build required" >> $GITHUB_STEP_SUMMARY
